export const CARD_DATA = {
  tecnologia: [
    { id: 'tech_laptop', name: 'Laptop', image: '/cards/tecnologia/tech_laptop.png' },
    { id: 'tech_smartphone', name: 'Smartphone', image: '/cards/tecnologia/tech_smartphone.png' },
    { id: 'tech_cpu', name: 'CPU', image: '/cards/tecnologia/tech_cpu.png' },
    { id: 'tech_robot', name: 'Robot', image: '/cards/tecnologia/tech_robot.png' },
    { id: 'tech_drone', name: 'Drone', image: '/cards/tecnologia/tech_drone.png' },
    { id: 'tech_vr', name: 'VR Headset', image: '/cards/tecnologia/tech_vr.png' },
    { id: 'tech_satellite', name: 'Satélite', image: '/cards/tecnologia/tech_satellite.png' },
    { id: 'tech_smartwatch', name: 'Smartwatch', image: '/cards/tecnologia/tech_smartwatch.png' },
    { id: 'tech_server', name: 'Servidor', image: '/cards/tecnologia/tech_server.png' },
    { id: 'tech_chip', name: 'Chip', image: '/cards/tecnologia/tech_chip.png' },
    { id: 'tech_rocket', name: 'Cohete', image: '/cards/tecnologia/tech_rocket.png' },
    { id: 'tech_hologram', name: 'Holograma', image: '/cards/tecnologia/tech_hologram.png' },
    { id: 'tech_ai_brain', name: 'Cerebro IA', image: '/cards/tecnologia/tech_ai_brain.png' },
    { id: 'tech_circuit', name: 'Circuito', image: '/cards/tecnologia/tech_circuit.png' },
    { id: 'tech_antenna', name: 'Antena', image: '/cards/tecnologia/tech_antenna.png' },
    { id: 'tech_camera', name: 'Cámara', image: '/cards/tecnologia/tech_camera.png' },
    { id: 'tech_printer3d', name: 'Impresora 3D', image: '/cards/tecnologia/tech_printer3d.png' },
    { id: 'tech_code', name: 'Código', image: '/cards/tecnologia/tech_code.png' },
    { id: 'tech_gamepad', name: 'Gamepad', image: '/cards/tecnologia/tech_gamepad.png' },
    { id: 'tech_headphones', name: 'Audífonos', image: '/cards/tecnologia/tech_headphones.png' },
  ],
  naturaleza: [
    { id: 'nat_leaf', name: 'Hoja', image: '/cards/naturaleza/nat_leaf.png' },
    { id: 'nat_lotus', name: 'Loto', image: '/cards/naturaleza/nat_lotus.png' },
    { id: 'nat_oak', name: 'Roble', image: '/cards/naturaleza/nat_oak.png' },
    { id: 'nat_mountain', name: 'Montaña', image: '/cards/naturaleza/nat_mountain.png' },
    { id: 'nat_river', name: 'Río', image: '/cards/naturaleza/nat_river.png' },
    { id: 'nat_sun', name: 'Sol', image: '/cards/naturaleza/nat_sun.png' },
    { id: 'nat_butterfly', name: 'Mariposa', image: '/cards/naturaleza/nat_butterfly.png' },
    { id: 'nat_cloud', name: 'Nube', image: '/cards/naturaleza/nat_cloud.png' },
    { id: 'nat_waterfall', name: 'Cascada', image: '/cards/naturaleza/nat_waterfall.png' },
    { id: 'nat_cactus', name: 'Cactus', image: '/cards/naturaleza/nat_cactus.png' },
    { id: 'nat_coral', name: 'Coral', image: '/cards/naturaleza/nat_coral.png' },
    { id: 'nat_moss', name: 'Musgo', image: '/cards/naturaleza/nat_moss.png' },
    { id: 'nat_waterdrop', name: 'Gota', image: '/cards/naturaleza/nat_waterdrop.png' },
    { id: 'nat_moon', name: 'Luna', image: '/cards/naturaleza/nat_moon.png' },
    { id: 'nat_volcano', name: 'Volcán', image: '/cards/naturaleza/nat_volcano.png' },
    { id: 'nat_rainbow', name: 'Arcoíris', image: '/cards/naturaleza/nat_rainbow.png' },
    { id: 'nat_star', name: 'Estrella', image: '/cards/naturaleza/nat_star.png' },
    { id: 'nat_crystal', name: 'Cristal', image: '/cards/naturaleza/nat_crystal.png' },
    { id: 'nat_mushroom', name: 'Hongo', image: '/cards/naturaleza/nat_mushroom.png' },
    { id: 'nat_feather', name: 'Pluma', image: '/cards/naturaleza/nat_feather.png' },
  ],
  animales: [
    { id: 'anim_lion', name: 'León', image: '/cards/animales/anim_lion.png' },
    { id: 'anim_eagle', name: 'Águila', image: '/cards/animales/anim_eagle.png' },
    { id: 'anim_dolphin', name: 'Delfín', image: '/cards/animales/anim_dolphin.png' },
    { id: 'anim_fox', name: 'Zorro', image: '/cards/animales/anim_fox.png' },
    { id: 'anim_owl', name: 'Búho', image: '/cards/animales/anim_owl.png' },
    { id: 'anim_wolf', name: 'Lobo', image: '/cards/animales/anim_wolf.png' },
    { id: 'anim_turtle', name: 'Tortuga', image: '/cards/animales/anim_turtle.png' },
    { id: 'anim_hummingbird', name: 'Colibrí', image: '/cards/animales/anim_hummingbird.png' },
    { id: 'anim_tiger', name: 'Tigre', image: '/cards/animales/anim_tiger.png' },
    { id: 'anim_bear', name: 'Oso', image: '/cards/animales/anim_bear.png' },
    { id: 'anim_snake', name: 'Serpiente', image: '/cards/animales/anim_snake.png' },
    { id: 'anim_horse', name: 'Caballo', image: '/cards/animales/anim_horse.png' },
    { id: 'anim_panda', name: 'Panda', image: '/cards/animales/anim_panda.png' },
    { id: 'anim_elephant', name: 'Elefante', image: '/cards/animales/anim_elephant.png' },
    { id: 'anim_shark', name: 'Tiburón', image: '/cards/animales/anim_shark.png' },
    { id: 'anim_chameleon', name: 'Camaleón', image: '/cards/animales/anim_chameleon.png' },
    { id: 'anim_penguin', name: 'Pingüino', image: '/cards/animales/anim_penguin.png' },
    { id: 'anim_octopus', name: 'Pulpo', image: '/cards/animales/anim_octopus.png' },
    { id: 'anim_phoenix', name: 'Fénix', image: '/cards/animales/anim_phoenix.png' },
    { id: 'anim_parrot', name: 'Loro', image: '/cards/animales/anim_parrot.png' },
  ],
};
